apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: meah4uupd-nodejs
  janus-idp.io/tekton: meah4uupd-nodejs
  backstage.io/kubernetes-id: meah4uupd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: meah4uupd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
