apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: meah4uupd-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: meah4uupd-nodejs 
  name: meah4uupd-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: meah4uupd-nodejs 
